server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name:
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8081/
          predicates:
            - Path=/user_service/**
        - id: board_service
          uri: http://localhost:8082/
          predicates:
            - Path=/board_service/**
        - id: quiz_service
          uri: http://localhost:8083/
          predicates:
            - Path=/quiz_service/**
        - id: global
          uri: http://localhost:8084/
          predicates:
            - Path=/global/**